FROM python:3.10

WORKDIR /app

COPY backend/requirements.txt .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

COPY backend ./backend
COPY ml_pipeline ./ml_pipeline
COPY model ./model
COPY data ./data

WORKDIR /app/backend

EXPOSE 8000

CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]